"""
generate_render_bat.py
======================
Generates a ready-to-run render_CHARNAME.bat for any character
in the newtoadd folder.

Usage (run from any terminal — no Blender needed):
  python generate_render_bat.py robowalker
  python generate_render_bat.py robowalker --mode meshy
  python generate_render_bat.py robowalker --mode mixamo --start 1 --end 60

The script scans  Characters/newtoadd/CHARNAME/fbx/fbx*/
and generates one Blender call per animation subfolder found.

Folder name → animation name mapping:
  fbxrun    → run
  fbxidle   → idle
  fbxattack → attack
  fbxwalk   → walk
  fbxdeath  → death
  fbxjump   → jump
  (any other fbxXXX → XXX)
"""

import os, sys

# ══════════════════════════════════════════════════════════════
#  ► SET THESE ONCE  (only need to change if paths move)
# ══════════════════════════════════════════════════════════════

BLENDER_EXE  = r"C:\Program Files\Blender Foundation\Blender 5.0\blender.exe"
MINISWG_ROOT = r"C:\Users\ryang\OneDrive\Documents\miniSWG"
NEWTOADD_DIR = os.path.join(MINISWG_ROOT, "Characters", "newtoadd")
LAUNCHER_PY  = os.path.join(MINISWG_ROOT, "Tools", "render_launcher.py")

# ══════════════════════════════════════════════════════════════

def detect_mode(char_dir: str) -> str:
    """Scan fbx filenames to guess meshy vs mixamo.
    Meshy AI files always start with 'Meshy_AI_'.
    Falls back to 'mixamo' if unknown.
    """
    fbx_root = os.path.join(char_dir, "fbx")
    if not os.path.isdir(fbx_root):
        return "mixamo"
    for root, _, files in os.walk(fbx_root):
        for f in files:
            if f.lower().endswith(".fbx"):
                if f.startswith("Meshy_AI_"):
                    return "meshy"
                return "mixamo"
    return "mixamo"

def find_fbx_anims(char_dir: str) -> list:
    """
    Scan char_dir/fbx/ for subfolders starting with 'fbx'.
    Returns list of (anim_name, fbx_folder_path) tuples.
    """
    fbx_root = os.path.join(char_dir, "fbx")
    if not os.path.isdir(fbx_root):
        print(f"  WARNING: No fbx/ folder found at {fbx_root}")
        return []

    anims = []
    for name in sorted(os.listdir(fbx_root)):
        full = os.path.join(fbx_root, name)
        if os.path.isdir(full) and name.lower().startswith("fbx"):
            # Strip the "fbx" prefix to get the animation name
            anim_name = name[3:].lower()  # fbxrun → run, fbxidle → idle
            if not anim_name:
                anim_name = "anim"
            anims.append((anim_name, full))
            print(f"  Found: {name}/ -> anim '{anim_name}'")
    return anims

def parse_args():
    args = {"mode": None, "start": None, "end": None, "step": None}
    argv = sys.argv[1:]
    if not argv:
        print("Usage: python generate_render_bat.py CHARNAME [meshy|mixamo] [--start N] [--end N]")
        print("  Mode can be a positional arg:  generate_render_bat.py robowalker meshy")
        print("  Or a flag:                     generate_render_bat.py robowalker --mode meshy")
        sys.exit(1)

    args["charname"] = argv[0]

    # Accept mode as plain second word: "robowalker meshy" or "robowalker mixamo"
    if len(argv) > 1 and argv[1] in ("meshy", "mixamo"):
        args["mode"] = argv[1]
        argv = [argv[0]] + argv[2:]

    i = 1
    while i < len(argv):
        key = argv[i].lstrip("-")
        if i + 1 < len(argv) and not argv[i+1].startswith("--"):
            args[key] = argv[i+1]
            i += 2
        else:
            i += 1
    return args

def generate(charname: str, mode: str = "mixamo",
             start: str = None, end: str = None, step: str = None):

    char_dir = os.path.join(NEWTOADD_DIR, charname)
    if not os.path.isdir(char_dir):
        print(f"ERROR: Character folder not found: {char_dir}")
        sys.exit(1)

    # Auto-detect mode from filenames if not explicitly set
    if not mode:
        mode = detect_mode(char_dir)
        print(f"\nAuto-detected mode: {mode}")
    else:
        print(f"\nMode: {mode} (specified)")

    print(f"Scanning {char_dir}...")
    anims = find_fbx_anims(char_dir)

    if not anims:
        print("ERROR: No fbxXXX subfolders found inside fbx/. Nothing to generate.")
        sys.exit(1)

    # Build bat content
    lines = []
    lines.append("@echo off")
    lines.append(f":: Auto-generated by generate_render_bat.py")
    lines.append(f":: Character: {charname}  |  Mode: {mode}")
    lines.append("::")
    lines.append(f'set BLENDER="{BLENDER_EXE}"')
    lines.append(f'set SCRIPT="{LAUNCHER_PY}"')
    lines.append(f'set CHAR="{char_dir}"')
    lines.append(f"set MODE={mode}")
    lines.append("")
    lines.append("echo ============================================================")
    lines.append(f"echo  Rendering {charname} sprites  [{mode} mode]")
    lines.append("echo ============================================================")
    lines.append("echo.")

    for i, (anim_name, fbx_folder) in enumerate(anims, start=1):
        output_dir = os.path.join(char_dir, anim_name)
        lines.append(f"echo [{i}/{len(anims)}] {anim_name.upper()}")

        # Build the blender command
        cmd_parts = [
            "%BLENDER% --background --python %SCRIPT% --",
            f'    --fbx "{fbx_folder}"',
            f'    --output "{output_dir}"',
            f"    --anim {anim_name} --mode %MODE%",
        ]
        if start: cmd_parts.append(f"    --start {start}")
        if end:   cmd_parts.append(f"    --end {end}")
        if step:  cmd_parts.append(f"    --step {step}")

        # Join with ^ line continuation
        lines.append(" ^\n".join(cmd_parts))
        lines.append("if errorlevel 1 goto :error")
        lines.append("echo.")

    lines.append("echo ============================================================")
    lines.append(f"echo  ALL DONE!  Check output folders in:")
    lines.append(f"echo  {char_dir}")
    lines.append("echo ============================================================")
    lines.append("pause")
    lines.append("exit /b 0")
    lines.append("")
    lines.append(":error")
    lines.append("echo.")
    lines.append("echo  ERROR: Blender returned an error. Check output above.")
    lines.append("pause")
    lines.append("exit /b 1")

    bat_path = os.path.join(char_dir, f"render_{charname}.bat")
    with open(bat_path, "w") as f:
        f.write("\n".join(lines))

    print(f"\nGenerated: {bat_path}")
    print(f"  Animations: {', '.join(a for a, _ in anims)}")
    print(f"  Mode:       {mode}")
    print(f"\nDouble-click render_{charname}.bat to start rendering.")

if __name__ == "__main__":
    args = parse_args()
    generate(
        charname = args["charname"],
        mode     = args.get("mode",  None),   # None = auto-detect
        start    = args.get("start", None),
        end      = args.get("end",   None),
        step     = args.get("step",  None),
    )
