"""
Blender Sprite Sheet Renderer
=============================
Renders the current scene's animated character from 8 isometric directions
and saves each direction as a horizontal strip, plus a combined grid sheet.

Usage in Blender:
  1. Open your .blend file with the rigged + animated character
  2. Go to Scripting tab (top menu bar)
  3. Click "New" to create a new text block
  4. Paste this entire script
  5. Edit OUTPUT_DIR below if needed
  6. Click "Run Script" (or Alt+P)

Output:
  - run_s.png, run_sw.png, run_w.png, etc. (one strip per direction)
  - run_spritesheet.png (combined 4-column grid)
"""

import bpy
import math
import os
from mathutils import Vector

# ══════════════════════════════════════════════════════════════
#  CONFIGURATION — Edit these to match your needs
# ══════════════════════════════════════════════════════════════

# Output folder (will be created if it doesn't exist)
OUTPUT_DIR = r"C:\Users\ryang\OneDrive\Desktop\Game dev\ASSET_DOWNLOADS\rendered_sprites"

# Animation name prefix for output files (e.g., "run", "idle", "attack")
ANIM_NAME = "run"

# Frame range — check your timeline in Blender for the correct range
FRAME_START = 1
FRAME_END = 60       # Adjust to your animation's last frame
FRAME_STEP = 1       # 1 = every frame, 2 = every other frame, etc.

# Render resolution per frame
FRAME_WIDTH = 512
FRAME_HEIGHT = 512

# Transparent background
USE_TRANSPARENT = True

# Camera distance from character (increase if character is cut off)
CAM_DISTANCE = 3.0

# Camera height (isometric angle — higher = more top-down)
CAM_HEIGHT = 2.0

# Character center height offset (adjust if camera aims too high/low)
CHAR_CENTER_Z = 0.8

# Spritesheet grid columns (for combined sheet)
GRID_COLS = 4

# 5 directions rendered, 3 more generated by horizontal flip
# Render: S, N, E, NE, SE
# Flip:   E->W, NE->NW, SE->SW
DIRECTIONS = [
    ("s",  0),
    ("n",  180),
    ("e",  270),
    ("ne", 225),
    ("se", 315),
]

# Flip mapping: source -> destination
FLIP_MAP = {
    "e":  "w",
    "ne": "nw",
    "se": "sw",
}

# ══════════════════════════════════════════════════════════════
#  CAMERA CONFIG — saves/loads camera settings so all anims
#  for the same character use identical framing.
#  Delete the .json file to reset camera settings.
# ══════════════════════════════════════════════════════════════

import json

CONFIG_FILE = os.path.join(OUTPUT_DIR, "_camera_config.json")

def save_camera_config():
    """Save camera settings so all animations match."""
    config = {
        "cam_distance": CAM_DISTANCE,
        "cam_height": CAM_HEIGHT,
        "char_center_z": CHAR_CENTER_Z,
        "frame_width": FRAME_WIDTH,
        "frame_height": FRAME_HEIGHT,
        "ortho_scale": 2.5,
    }
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    with open(CONFIG_FILE, 'w') as f:
        json.dump(config, f, indent=2)
    print(f"  Camera config saved: {CONFIG_FILE}")

def load_camera_config():
    """Load saved camera settings if they exist. Returns True if loaded."""
    global CAM_DISTANCE, CAM_HEIGHT, CHAR_CENTER_Z, FRAME_WIDTH, FRAME_HEIGHT
    if not os.path.exists(CONFIG_FILE):
        return False
    try:
        with open(CONFIG_FILE, 'r') as f:
            config = json.load(f)
        CAM_DISTANCE = config.get("cam_distance", CAM_DISTANCE)
        CAM_HEIGHT = config.get("cam_height", CAM_HEIGHT)
        CHAR_CENTER_Z = config.get("char_center_z", CHAR_CENTER_Z)
        FRAME_WIDTH = config.get("frame_width", FRAME_WIDTH)
        FRAME_HEIGHT = config.get("frame_height", FRAME_HEIGHT)
        print(f"  Camera config loaded from: {CONFIG_FILE}")
        print(f"  CAM_DISTANCE={CAM_DISTANCE}, CAM_HEIGHT={CAM_HEIGHT}, CHAR_CENTER_Z={CHAR_CENTER_Z}")
        return True
    except:
        return False

# ══════════════════════════════════════════════════════════════
#  SCRIPT — Don't edit below unless you know what you're doing
# ══════════════════════════════════════════════════════════════

def setup_render_settings():
    """Configure render settings for sprite output."""
    scene = bpy.context.scene
    # Try EEVEE variants (name changed across Blender versions)
    for engine in ['BLENDER_EEVEE_NEXT', 'BLENDER_EEVEE', 'BLENDER_WORKBENCH']:
        try:
            scene.render.engine = engine
            break
        except:
            continue
    scene.render.resolution_x = FRAME_WIDTH
    scene.render.resolution_y = FRAME_HEIGHT
    scene.render.resolution_percentage = 100
    scene.render.image_settings.file_format = 'PNG'
    scene.render.image_settings.color_mode = 'RGBA'
    scene.render.image_settings.compression = 15

    if USE_TRANSPARENT:
        scene.render.film_transparent = True

    # Disable unnecessary features for speed
    try:
        scene.eevee.use_bloom = False
        scene.eevee.use_motion_blur = False
    except:
        pass  # Not all Blender versions have these

def setup_camera():
    """Create or get the sprite render camera."""
    cam_name = "SpriteCamera"

    # Remove existing sprite camera if any
    if cam_name in bpy.data.objects:
        bpy.data.objects.remove(bpy.data.objects[cam_name], do_unlink=True)

    # Create new camera
    cam_data = bpy.data.cameras.new(name=cam_name)
    cam_data.type = 'ORTHO'  # Orthographic for clean 2D look
    cam_data.ortho_scale = 2.5  # Adjust if character is too big/small in frame

    cam_obj = bpy.data.objects.new(cam_name, cam_data)
    bpy.context.scene.collection.objects.link(cam_obj)
    bpy.context.scene.camera = cam_obj

    return cam_obj

def position_camera(cam_obj, angle_deg):
    """Position camera at isometric angle around the character."""
    angle_rad = math.radians(angle_deg)

    # Camera orbits around (0, 0, CHAR_CENTER_Z)
    x = math.sin(angle_rad) * CAM_DISTANCE
    y = -math.cos(angle_rad) * CAM_DISTANCE
    z = CAM_HEIGHT + CHAR_CENTER_Z

    cam_obj.location = Vector((x, y, z))

    # Point camera at character center
    target = Vector((0, 0, CHAR_CENTER_Z))
    direction = target - cam_obj.location
    rot_quat = direction.to_track_quat('-Z', 'Y')
    cam_obj.rotation_euler = rot_quat.to_euler()

def setup_lighting():
    """Set up flat, even lighting for sprite rendering."""
    # Remove all existing lights
    for obj in bpy.data.objects:
        if obj.type == 'LIGHT':
            bpy.data.objects.remove(obj, do_unlink=True)

    # Key light (main, from above-front)
    key_data = bpy.data.lights.new(name="KeyLight", type='SUN')
    key_data.energy = 3.0
    key_obj = bpy.data.objects.new("KeyLight", key_data)
    bpy.context.scene.collection.objects.link(key_obj)
    key_obj.rotation_euler = (math.radians(45), 0, math.radians(-30))

    # Fill light (softer, from opposite side)
    fill_data = bpy.data.lights.new(name="FillLight", type='SUN')
    fill_data.energy = 1.5
    fill_obj = bpy.data.objects.new("FillLight", fill_data)
    bpy.context.scene.collection.objects.link(fill_obj)
    fill_obj.rotation_euler = (math.radians(60), 0, math.radians(150))

    # Ambient / world lighting
    world = bpy.context.scene.world
    if world is None:
        world = bpy.data.worlds.new("World")
        bpy.context.scene.world = world
    world.use_nodes = True
    bg_node = world.node_tree.nodes.get("Background")
    if bg_node:
        bg_node.inputs[0].default_value = (0.15, 0.15, 0.15, 1.0)  # Slight ambient
        bg_node.inputs[1].default_value = 0.5  # Strength

def make_materials_matte():
    """Reduce shininess on all materials for a cleaner sprite look."""
    for mat in bpy.data.materials:
        if mat.use_nodes:
            for node in mat.node_tree.nodes:
                if node.type == 'BSDF_PRINCIPLED':
                    # Increase roughness (less shiny)
                    if 'Roughness' in node.inputs:
                        node.inputs['Roughness'].default_value = 0.25
                    # Reduce specular
                    if 'Specular IOR Level' in node.inputs:
                        node.inputs['Specular IOR Level'].default_value = 0.1
                    elif 'Specular' in node.inputs:
                        node.inputs['Specular'].default_value = 0.1

def render_direction(cam_obj, dir_name, angle_deg, output_dir):
    """Render all frames for one direction, save as individual PNGs."""
    position_camera(cam_obj, angle_deg)

    dir_folder = os.path.join(output_dir, dir_name)
    os.makedirs(dir_folder, exist_ok=True)

    scene = bpy.context.scene
    frames_rendered = 0

    for frame in range(FRAME_START, FRAME_END + 1, FRAME_STEP):
        scene.frame_set(frame)
        filepath = os.path.join(dir_folder, f"frame_{frame:04d}.png")
        scene.render.filepath = filepath
        bpy.ops.render.render(write_still=True)
        frames_rendered += 1
        print(f"  Rendered {dir_name} frame {frame}/{FRAME_END}")

    return frames_rendered

def combine_to_strip(dir_name, output_dir, num_frames):
    """Combine individual frame PNGs into a horizontal strip."""
    # We need to use Blender's compositor or PIL-like approach
    # Since we can't guarantee PIL in Blender, use Blender's image API

    dir_folder = os.path.join(output_dir, dir_name)

    # Load first image to get dimensions
    first_path = os.path.join(dir_folder, f"frame_{FRAME_START:04d}.png")
    first_img = bpy.data.images.load(first_path)
    fw = first_img.size[0]
    fh = first_img.size[1]
    bpy.data.images.remove(first_img)

    # Create strip image
    strip_name = f"{ANIM_NAME}_{dir_name}_strip"
    strip = bpy.data.images.new(strip_name, width=fw * num_frames, height=fh, alpha=True)
    strip_pixels = [0.0] * (fw * num_frames * fh * 4)

    frame_idx = 0
    for frame in range(FRAME_START, FRAME_END + 1, FRAME_STEP):
        frame_path = os.path.join(dir_folder, f"frame_{frame:04d}.png")
        frame_img = bpy.data.images.load(frame_path)
        frame_pixels = list(frame_img.pixels)

        # Copy pixels into strip (Blender stores bottom-to-top)
        for y in range(fh):
            for x in range(fw):
                src_idx = (y * fw + x) * 4
                dst_idx = (y * (fw * num_frames) + (frame_idx * fw + x)) * 4
                strip_pixels[dst_idx:dst_idx+4] = frame_pixels[src_idx:src_idx+4]

        bpy.data.images.remove(frame_img)
        frame_idx += 1

    strip.pixels = strip_pixels
    strip_path = os.path.join(output_dir, f"{ANIM_NAME}_{dir_name}.png")
    strip.filepath_raw = strip_path
    strip.file_format = 'PNG'
    strip.save()
    bpy.data.images.remove(strip)
    print(f"  Saved strip: {strip_path}")

def combine_to_grid(output_dir, num_frames):
    """Combine all direction strips into a single grid spritesheet."""
    # Load one frame to get dimensions
    first_dir = DIRECTIONS[0][0]
    first_path = os.path.join(output_dir, first_dir, f"frame_{FRAME_START:04d}.png")
    first_img = bpy.data.images.load(first_path)
    fw = first_img.size[0]
    fh = first_img.size[1]
    bpy.data.images.remove(first_img)

    total_frames = num_frames * len(DIRECTIONS)
    rows = math.ceil(total_frames / GRID_COLS)

    grid = bpy.data.images.new("spritesheet", width=fw * GRID_COLS, height=fh * rows, alpha=True)
    grid_pixels = [0.0] * (fw * GRID_COLS * fh * rows * 4)

    global_frame = 0
    for dir_name, _ in DIRECTIONS:
        dir_folder = os.path.join(output_dir, dir_name)
        for frame in range(FRAME_START, FRAME_END + 1, FRAME_STEP):
            col = global_frame % GRID_COLS
            row = rows - 1 - (global_frame // GRID_COLS)  # Blender is bottom-up

            frame_path = os.path.join(dir_folder, f"frame_{frame:04d}.png")
            frame_img = bpy.data.images.load(frame_path)
            frame_pixels = list(frame_img.pixels)

            for y in range(fh):
                for x in range(fw):
                    src_idx = (y * fw + x) * 4
                    dst_x = col * fw + x
                    dst_y = row * fh + y
                    dst_idx = (dst_y * (fw * GRID_COLS) + dst_x) * 4
                    if dst_idx + 3 < len(grid_pixels):
                        grid_pixels[dst_idx:dst_idx+4] = frame_pixels[src_idx:src_idx+4]

            bpy.data.images.remove(frame_img)
            global_frame += 1

    grid.pixels = grid_pixels
    grid_path = os.path.join(output_dir, f"{ANIM_NAME}_spritesheet.png")
    grid.filepath_raw = grid_path
    grid.file_format = 'PNG'
    grid.save()
    bpy.data.images.remove(grid)
    print(f"\nSaved grid spritesheet: {grid_path}")
    print(f"  {GRID_COLS} columns x {rows} rows, {fw}x{fh} per cell")

# ══════════════════════════════════════════════════════════════
#  MAIN
# ══════════════════════════════════════════════════════════════

def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    print("=" * 60)
    print("  SPRITE SHEET RENDERER")
    print("=" * 60)

    # Load saved camera config if it exists (ensures consistent framing across anims)
    if load_camera_config():
        print("  Using saved camera settings (delete _camera_config.json to reset)")
    else:
        print("  No saved config — using settings from script header")

    # Setup
    print("\n[1/6] Setting up render settings...")
    setup_render_settings()

    print("[2/6] Setting up camera...")
    cam = setup_camera()

    print("[3/6] Setting up lighting...")
    setup_lighting()

    print("[3.5] Making materials matte...")
    make_materials_matte()

    # Render each direction
    print(f"\n[4/5] Rendering {len(DIRECTIONS)} directions...")
    num_frames = len(range(FRAME_START, FRAME_END + 1, FRAME_STEP))

    for dir_name, angle in DIRECTIONS:
        print(f"\n  --- {dir_name.upper()} ({angle}°) ---")
        render_direction(cam, dir_name, angle, OUTPUT_DIR)
        combine_to_strip(dir_name, OUTPUT_DIR, num_frames)

    # Clean up individual frame folders (keep only the strips)
    print(f"\n[5/5] Cleaning up individual frame folders...")
    import shutil
    for dir_name, _ in DIRECTIONS:
        dir_folder = os.path.join(OUTPUT_DIR, dir_name)
        if os.path.isdir(dir_folder):
            shutil.rmtree(dir_folder)
            print(f"  Deleted: {dir_folder}")

    # Save camera config for future renders of same character
    save_camera_config()

    # Generate flipped directions (E->W, NE->NW, SE->SW)
    print(f"\n[6/6] Generating flipped directions...")
    try:
        from PIL import Image as PILImage
        for src_dir, dst_dir in FLIP_MAP.items():
            src_path = os.path.join(OUTPUT_DIR, f"{ANIM_NAME}_{src_dir}.png")
            dst_path = os.path.join(OUTPUT_DIR, f"{ANIM_NAME}_{dst_dir}.png")
            if os.path.exists(src_path):
                img = PILImage.open(src_path)
                flipped = img.transpose(PILImage.FLIP_LEFT_RIGHT)
                flipped.save(dst_path)
                print(f"  Flipped: {ANIM_NAME}_{src_dir}.png -> {ANIM_NAME}_{dst_dir}.png")
            else:
                print(f"  WARNING: {src_path} not found, skipping flip")
    except ImportError:
        print("  PIL not available — install Pillow to enable auto-flip")
        print("  You can manually flip E->W, NE->NW, SE->SW in GIMP/Photoshop")

    print("\n" + "=" * 60)
    print("  DONE! Check output at:")
    print(f"  {OUTPUT_DIR}")
    print(f"  Rendered: {ANIM_NAME}_s, _n, _e, _ne, _se")
    print(f"  Flipped:  {ANIM_NAME}_w, _nw, _sw")
    print("=" * 60)

# Run it
main()
