"""
Blender Sprite Sheet Renderer — Universal Edition
==================================================
One script for both Meshy (in-place) and Mixamo (root-motion) characters.

  MODE = "meshy"   — fixed camera, works for Meshy AI / GLB / hand-made rigs
  MODE = "mixamo" — per-frame character tracking + auto-fit ortho scale

Mixamo import settings  (File > Import > FBX):
  Scale = 0.01  (Mixamo exports at 100x scale)
  Use Pre/Post Rotation: ON

Meshy import settings  (File > Import > FBX or GLB):
  Leave scale at 1.0 unless the character looks tiny/huge

Usage:
  1. Import your model
  2. Open Scripting tab, paste / open this script
  3. Set MODE, OUTPUT_DIR, ANIM_NAME, FRAME_START/END below
  4. Run Script (Alt+P)

Output per direction  (5 total — w/nw/sw handled via flip_h in Godot):
  run_s.png  run_n.png  run_e.png  run_ne.png  run_se.png
"""

import bpy, math, os, json, shutil
from mathutils import Vector

# ══════════════════════════════════════════════════════════════
#  ► CHANGE THESE EVERY RUN
# ══════════════════════════════════════════════════════════════

# "meshy"  — static/in-place character (Meshy AI, hand-made rigs)
# "mixamo" — root-motion character (Mixamo FBX, camera follows every frame)
MODE = "meshy"

OUTPUT_DIR = r"C:\Users\ryang\OneDrive\Desktop\Game dev\ASSET_DOWNLOADS\rendered_sprites"
ANIM_NAME  = "run"   # prefix for output files:  run_s.png, run_ne.png …

# Frame range — None = auto-detect from Blender timeline
FRAME_START = None
FRAME_END   = None
FRAME_STEP  = 1     # 1 = every frame, 2 = every other, etc.

# ══════════════════════════════════════════════════════════════
#  CAMERA & FRAME OVERRIDES
#  All default to None — sensible values are chosen automatically
#  based on MODE. Set to a number to force a specific value.
# ══════════════════════════════════════════════════════════════

FRAME_WIDTH   = None   # None → 512  (both modes)
FRAME_HEIGHT  = None   # None → 512  (meshy)  /  640  (mixamo — taller for humanoids)

CAM_DISTANCE  = None   # None → 3.0  (meshy)  /  4.5  (mixamo)
CAM_HEIGHT    = None   # None → 2.0  (meshy)  /  2.8  (mixamo)
CHAR_CENTER_Z = None   # None → 0.8  (meshy)  /  0.95 (mixamo — Mixamo chars are taller)

# Fixed ortho scale — used in meshy mode, or as fallback if auto-fit fails
ORTHO_SCALE = 2.5

# ── Mixamo auto-fit ───────────────────────────────────────────
# Scans ~30 sample frames, measures bounding box, calculates the exact
# ortho_scale needed so no limb ever leaves the frame.
AUTO_FIT_CAMERA = True    # only active in mixamo mode
ORTHO_PADDING   = 1.18   # multiply result by this (1.18 = 18% breathing room)

# ══════════════════════════════════════════════════════════════
#  OTHER SETTINGS
# ══════════════════════════════════════════════════════════════

USE_TRANSPARENT = True

# Skip frames whose PNG already exists — safe to re-run after a crash.
# The script will pick up exactly where it left off.
SKIP_EXISTING = True

# Split long animations into numbered chunks  (idle1/, idle2/, …)
# Set to 0 to always produce one strip per direction.
CHUNK_SIZE = 40

# 5 directions rendered, 3 more generated by horizontal flip
DIRECTIONS = [
    ("s",  0),
    ("n",  180),
    ("e",  270),
    ("ne", 225),
    ("se", 315),
]
GRID_COLS = 4

# ══════════════════════════════════════════════════════════════
#  FRAME RANGE AUTO-DETECTION
# ══════════════════════════════════════════════════════════════

def _iter_action_fcurves(action):
    """Yield fcurves from an action — handles Blender 4.x and 5.0 APIs.

    Blender 4.x: action.fcurves (direct attribute, non-empty)
    Blender 5.0: action.layers[].strips[].channelbags[].fcurves (slotted system)
    If action.fcurves exists but is empty (5.0 compat shim), fall through to
    the layered system so keyframes are not missed.
    """
    if hasattr(action, 'fcurves'):
        curves = list(action.fcurves)
        if curves:
            yield from curves
            return
    for layer in getattr(action, 'layers', []):
        for strip in getattr(layer, 'strips', []):
            if hasattr(strip, 'fcurves'):
                yield from strip.fcurves
                continue
            for cb in getattr(strip, 'channelbags', []):
                yield from getattr(cb, 'fcurves', [])

def detect_anim_frame_range() -> tuple:
    """Read the actual keyframe extent by scanning f-curves and NLA strips.

    Method 1 — f-curve keyframe points in bpy.data.actions:
      Works for FBX imports where keyframes live directly on the action.

    Method 2 — NLA strip scene-space frame ranges:
      GLB/GLTF (Meshy) imports bake animations into NLA strips.  The action
      exists in bpy.data.actions but its fcurves have no keyframe points —
      all timing lives in the strip.  strip.frame_start/end are the scene-
      space frames that actually animate the character, so we use those.

    Falls back to scene.frame_start/end if nothing is found either way.
    """
    scene = bpy.context.scene
    start = float('inf')
    end   = float('-inf')

    # Method 1: f-curve keyframe points
    for action in bpy.data.actions:
        for fcurve in _iter_action_fcurves(action):
            for kp in fcurve.keyframe_points:
                if kp.co.x < start: start = kp.co.x
                if kp.co.x > end:   end   = kp.co.x

    # Method 2: NLA strips (GLB/Meshy baked animations have no raw keypoints)
    for obj in bpy.data.objects:
        ad = getattr(obj, 'animation_data', None)
        if ad is None: continue
        for track in getattr(ad, 'nla_tracks', []):
            for strip in track.strips:
                fs = getattr(strip, 'frame_start', None)
                fe = getattr(strip, 'frame_end',   None)
                if fs is not None and fs < start: start = fs
                if fe is not None and fe > end:   end   = fe

    if start == float('inf'):
        print("  Frame range: no keyframes or NLA strips found, using scene range")
        return int(scene.frame_start), int(scene.frame_end)
    s, e = int(round(start)), int(round(end))
    print(f"  Detected keyframe range: {s}–{e}  ({e - s + 1} frames)")
    return s, e

# ══════════════════════════════════════════════════════════════
#  RESOLVE DEFAULTS FROM MODE  (don't edit below this line)
# ══════════════════════════════════════════════════════════════

def _resolve_defaults():
    global FRAME_WIDTH, FRAME_HEIGHT, CAM_DISTANCE, CAM_HEIGHT, CHAR_CENTER_Z
    mixamo = (MODE == "mixamo")
    if FRAME_WIDTH   is None: FRAME_WIDTH   = 512
    if FRAME_HEIGHT  is None: FRAME_HEIGHT  = 640  if mixamo else 512
    if CAM_DISTANCE  is None: CAM_DISTANCE  = 4.5  if mixamo else 3.0
    if CAM_HEIGHT    is None: CAM_HEIGHT    = 2.8  if mixamo else 2.0
    if CHAR_CENTER_Z is None: CHAR_CENTER_Z = 0.95 if mixamo else 0.8

# ══════════════════════════════════════════════════════════════
#  CAMERA CONFIG  (persists ortho_scale across multiple anim renders)
# ══════════════════════════════════════════════════════════════

def _config_path():
    return os.path.join(OUTPUT_DIR, f"_{MODE}_camera_config.json")

def save_camera_config(ortho_scale_used):
    cfg = {
        "mode": MODE,
        "cam_distance": CAM_DISTANCE, "cam_height": CAM_HEIGHT,
        "char_center_z": CHAR_CENTER_Z,
        "frame_width": FRAME_WIDTH, "frame_height": FRAME_HEIGHT,
        "ortho_scale": ortho_scale_used,
    }
    with open(_config_path(), 'w') as f:
        json.dump(cfg, f, indent=2)
    print(f"  Config saved: {_config_path()}")

def load_camera_config():
    """Return saved ortho_scale if config exists, else None."""
    p = _config_path()
    if not os.path.exists(p):
        return None
    try:
        with open(p) as f:
            val = json.load(f).get("ortho_scale")
        print(f"  Loaded {MODE} config: ortho_scale={val}")
        return val
    except Exception:
        return None

# ══════════════════════════════════════════════════════════════
#  RENDER SETUP
# ══════════════════════════════════════════════════════════════

def setup_render_settings():
    scene = bpy.context.scene
    for engine in ['BLENDER_EEVEE_NEXT', 'BLENDER_EEVEE', 'BLENDER_WORKBENCH']:
        try:
            scene.render.engine = engine
            break
        except Exception:
            continue
    scene.render.resolution_x = FRAME_WIDTH
    scene.render.resolution_y = FRAME_HEIGHT
    scene.render.resolution_percentage = 100
    scene.render.image_settings.file_format = 'PNG'
    scene.render.image_settings.color_mode  = 'RGBA'
    scene.render.image_settings.compression = 15
    if USE_TRANSPARENT:
        scene.render.film_transparent = True
    try:
        scene.eevee.use_bloom       = False
        scene.eevee.use_motion_blur = False
    except Exception:
        pass

def setup_camera(ortho_scale):
    cam_name = "SpriteCamera"
    if cam_name in bpy.data.objects:
        bpy.data.objects.remove(bpy.data.objects[cam_name], do_unlink=True)
    cam_data = bpy.data.cameras.new(name=cam_name)
    cam_data.type        = 'ORTHO'
    cam_data.ortho_scale = ortho_scale
    cam_obj = bpy.data.objects.new(cam_name, cam_data)
    bpy.context.scene.collection.objects.link(cam_obj)
    bpy.context.scene.camera = cam_obj
    return cam_obj

def setup_lighting():
    for obj in bpy.data.objects:
        if obj.type == 'LIGHT':
            bpy.data.objects.remove(obj, do_unlink=True)
    for name, energy, rot in [
        ("KeyLight",  3.0, (math.radians(45),  0, math.radians(-30))),
        ("FillLight", 1.5, (math.radians(60),  0, math.radians(150))),
        ("RimLight",  0.8, (math.radians(-30), 0, math.radians(60))),
    ]:
        d = bpy.data.lights.new(name=name, type='SUN')
        d.energy = energy
        o = bpy.data.objects.new(name, d)
        bpy.context.scene.collection.objects.link(o)
        o.rotation_euler = rot
    world = bpy.context.scene.world
    if world is None:
        world = bpy.data.worlds.new("World")
        bpy.context.scene.world = world
    world.use_nodes = True
    bg = world.node_tree.nodes.get("Background")
    if bg:
        bg.inputs[0].default_value = (0.15, 0.15, 0.15, 1.0)
        bg.inputs[1].default_value = 0.5

def make_materials_matte():
    for mat in bpy.data.materials:
        if mat.use_nodes:
            for node in mat.node_tree.nodes:
                if node.type == 'BSDF_PRINCIPLED':
                    if 'Roughness' in node.inputs:
                        node.inputs['Roughness'].default_value = 0.25
                    for key in ('Specular IOR Level', 'Specular'):
                        if key in node.inputs:
                            node.inputs[key].default_value = 0.1
                            break

# ══════════════════════════════════════════════════════════════
#  CHARACTER TRACKING
# ══════════════════════════════════════════════════════════════

def _get_mesh_objects():
    return [o for o in bpy.context.scene.objects if o.type == 'MESH' and o.visible_get()]

def get_char_center_this_frame():
    """Return the world-space point the camera should orbit this frame.

    mixamo mode: reads the armature's actual world translation each frame,
                 so root-motion animations never leave the frame.
    meshy mode:  returns world origin + CHAR_CENTER_Z (character is static).
    """
    if MODE == "mixamo":
        # 1. Prefer armature — Mixamo rigs always have one
        for obj in bpy.context.scene.objects:
            if obj.type == 'ARMATURE' and obj.visible_get():
                loc = obj.matrix_world.translation
                return Vector((loc.x, loc.y, loc.z + CHAR_CENTER_Z))
        # 2. Fallback: average bounding box of all meshes
        meshes = _get_mesh_objects()
        if meshes:
            pts = [obj.matrix_world @ Vector(c)
                   for obj in meshes for c in obj.bound_box]
            xs = [p.x for p in pts]; ys = [p.y for p in pts]
            return Vector(((min(xs)+max(xs))*0.5,
                           (min(ys)+max(ys))*0.5,
                           CHAR_CENTER_Z))
    # meshy / fallback
    return Vector((0.0, 0.0, CHAR_CENTER_Z))

def position_camera(cam_obj, angle_deg, target=None):
    """Orbit the camera around target at the given horizontal angle."""
    if target is None:
        target = Vector((0.0, 0.0, CHAR_CENTER_Z))
    a = math.radians(angle_deg)
    cam_obj.location = Vector((
        target.x + math.sin(a) * CAM_DISTANCE,
        target.y - math.cos(a) * CAM_DISTANCE,
        target.z + CAM_HEIGHT,
    ))
    direction = target - cam_obj.location
    cam_obj.rotation_euler = direction.to_track_quat('-Z', 'Y').to_euler()

# ══════════════════════════════════════════════════════════════
#  AUTO-FIT ORTHO SCALE  (mixamo mode only)
# ══════════════════════════════════════════════════════════════

def _scan_bbox_relative_to_center():
    """Sample ~30 frames and measure the bounding box RELATIVE to the
    character's own center each frame.  This isolates limb-swing from
    root-motion translation so the result is accurate for any direction."""
    scene  = bpy.context.scene
    meshes = _get_mesh_objects()
    if not meshes:
        print("  WARNING: No visible meshes found — auto-fit skipped.")
        return None

    INF = float('inf')
    mn = [INF, INF, INF]; mx = [-INF, -INF, -INF]
    step = max(1, (FRAME_END - FRAME_START + 1) // 30)

    for frame in range(FRAME_START, FRAME_END + 1, step):
        scene.frame_set(frame)
        center = get_char_center_this_frame()
        for obj in meshes:
            for corner in obj.bound_box:
                wp  = obj.matrix_world @ Vector(corner)
                rel = [wp.x - center.x, wp.y - center.y, wp.z - center.z]
                for i in range(3):
                    if rel[i] < mn[i]: mn[i] = rel[i]
                    if rel[i] > mx[i]: mx[i] = rel[i]

    print(f"  BBox (relative to char center):")
    print(f"    X[{mn[0]:.2f}, {mx[0]:.2f}]  "
          f"Y[{mn[1]:.2f}, {mx[1]:.2f}]  "
          f"Z[{mn[2]:.2f}, {mx[2]:.2f}]")
    return tuple(mn + mx)

def _calc_auto_ortho_scale(bbox):
    """Convert bounding box to the ortho_scale that fits the character
    from any of the 5 camera angles with ORTHO_PADDING breathing room."""
    min_x, min_y, min_z, max_x, max_y, max_z = bbox
    aspect   = FRAME_WIDTH / FRAME_HEIGHT
    vertical = max_z - min_z
    xy_diag  = math.sqrt((max_x - min_x)**2 + (max_y - min_y)**2)
    needed   = max(vertical, xy_diag / aspect)
    result   = needed * ORTHO_PADDING
    print(f"  Auto-fit: Z_height={vertical:.2f}  XY_diag={xy_diag:.2f}  "
          f"needed={needed:.2f}  → ortho_scale={result:.3f}  "
          f"(×{ORTHO_PADDING} padding)")
    return result

# ══════════════════════════════════════════════════════════════
#  RENDERING
# ══════════════════════════════════════════════════════════════

def render_direction(cam_obj, dir_name, angle_deg, output_dir):
    """Render all frames for one direction.

    In mixamo mode the camera re-centres on the armature every frame,
    so root-motion animations stay perfectly framed throughout.
    In meshy mode the camera is fixed (character is in-place).
    """
    dir_folder = os.path.join(output_dir, dir_name)
    os.makedirs(dir_folder, exist_ok=True)

    scene = bpy.context.scene
    rendered = skipped = 0

    for frame in range(FRAME_START, FRAME_END + 1, FRAME_STEP):
        filepath = os.path.join(dir_folder, f"frame_{frame:04d}.png")

        if SKIP_EXISTING and os.path.exists(filepath):
            skipped += 1
            continue

        scene.frame_set(frame)
        bpy.context.view_layer.update()   # force pose eval (needed for GLB/NLA rigs)
        target = get_char_center_this_frame()
        position_camera(cam_obj, angle_deg, target)

        scene.render.filepath = filepath
        bpy.ops.render.render(write_still=True)
        rendered += 1

        extra = f"  center=({target.x:.2f},{target.y:.2f})" if MODE == "mixamo" else ""
        print(f"  {dir_name} frame {frame}/{FRAME_END}{extra}")

    if skipped:
        print(f"  Skipped {skipped} already-rendered frames")
    return rendered

# ══════════════════════════════════════════════════════════════
#  STRIP / SHEET ASSEMBLY
#
#  PIL path (recommended — install Pillow in Blender's Python):
#    Assembles strips one frame at a time.  Only one frame ever
#    lives in RAM.  Safe for 500+ frames.
#
#  Blender fallback (no Pillow):
#    Loads all frame pixels as Python float lists simultaneously.
#    Memory usage: ~37 MB per frame at 512×640 → crashes ~80-100 frames.
#    CHUNK_SIZE limits each strip to keep it under that threshold.
# ══════════════════════════════════════════════════════════════

def _write_strip_pil(frame_paths, out_path):
    """Assemble a strip from file paths using PIL — one frame at a time."""
    from PIL import Image as PILImage
    first  = PILImage.open(frame_paths[0]).convert("RGBA")
    fw, fh = first.size
    strip  = PILImage.new("RGBA", (fw * len(frame_paths), fh))
    strip.paste(first, (0, 0))
    for i, fp in enumerate(frame_paths[1:], start=1):
        strip.paste(PILImage.open(fp).convert("RGBA"), (i * fw, 0))
    strip.save(out_path)
    print(f"  Saved: {out_path}  ({len(frame_paths)} frames, PIL)")

def _write_strip_blender(frame_paths, out_path):
    """Assemble a strip using Blender's image API — fallback when PIL is absent."""
    first_img = bpy.data.images.load(frame_paths[0])
    fw, fh    = first_img.size[0], first_img.size[1]
    n         = len(frame_paths)
    img       = bpy.data.images.new(os.path.basename(out_path),
                                     width=fw * n, height=fh, alpha=True)
    px = [0.0] * (fw * n * fh * 4)
    for fi, fp in enumerate([frame_paths[0]] + list(frame_paths[1:])):
        src    = first_img if fi == 0 else bpy.data.images.load(fp)
        src_px = list(src.pixels)
        for y in range(fh):
            for x in range(fw):
                si = (y * fw + x) * 4
                di = (y * fw * n + fi * fw + x) * 4
                px[di:di+4] = src_px[si:si+4]
        bpy.data.images.remove(src)
    img.pixels = px
    img.filepath_raw = out_path
    img.file_format  = 'PNG'
    img.save()
    bpy.data.images.remove(img)
    print(f"  Saved: {out_path}  ({n} frames, Blender fallback)")

def _write_strip(frame_paths, out_path):
    """Write a strip, using PIL if available, Blender pixel API otherwise."""
    try:
        _write_strip_pil(frame_paths, out_path)
    except ImportError:
        _write_strip_blender(frame_paths, out_path)

def combine_to_strip(dir_name, output_dir, num_frames):
    """Combine individual frame PNGs into strip(s).

    Returns list of (part_label, strip_path) — one entry normally,
    multiple when CHUNK_SIZE splits a long animation.

    With PIL installed: no frame-count limit (assembles one frame at a time).
    Without PIL: limited by CHUNK_SIZE to avoid out-of-memory crashes.
    """
    dir_folder   = os.path.join(output_dir, dir_name)
    all_paths    = [
        os.path.join(dir_folder, f"frame_{frame:04d}.png")
        for frame in range(FRAME_START, FRAME_END + 1, FRAME_STEP)
    ]

    # CHUNK_SIZE always respected — PIL just removes the memory crash risk.
    chunk = CHUNK_SIZE if CHUNK_SIZE > 0 else num_frames
    try:
        import PIL  # noqa — just confirming available for _write_strip
    except ImportError:
        if CHUNK_SIZE == 0 or chunk > 40:
            chunk = 40

    results = []

    if num_frames <= chunk:
        out = os.path.join(output_dir, f"{ANIM_NAME}_{dir_name}.png")
        _write_strip(all_paths, out)
        results.append((ANIM_NAME, out))
    else:
        n_parts = math.ceil(num_frames / chunk)
        print(f"  {num_frames} frames → {n_parts} parts of {chunk}  "
              f"(install Pillow to remove this limit)")
        for pi in range(n_parts):
            # Insert underscore when ANIM_NAME already ends with a digit
            # so "attack1" → "attack1_2", not "attack12"
            sep   = "_" if ANIM_NAME and ANIM_NAME[-1].isdigit() else ""
            label = f"{ANIM_NAME}{sep}{pi+1}"
            paths    = all_paths[pi*chunk : (pi+1)*chunk]
            part_dir = os.path.join(output_dir, label)
            os.makedirs(part_dir, exist_ok=True)
            out = os.path.join(part_dir, f"{label}_{dir_name}.png")
            _write_strip(paths, out)
            results.append((label, out))

    return results

# ══════════════════════════════════════════════════════════════
#  MAIN
# ══════════════════════════════════════════════════════════════

def main():
    global FRAME_START, FRAME_END
    _resolve_defaults()

    if FRAME_START is None or FRAME_END is None:
        detected_start, detected_end = detect_anim_frame_range()
        if FRAME_START is None: FRAME_START = detected_start
        if FRAME_END   is None: FRAME_END   = detected_end

    os.makedirs(OUTPUT_DIR, exist_ok=True)

    num_frames    = len(range(FRAME_START, FRAME_END + 1, FRAME_STEP))
    total_renders = num_frames * len(DIRECTIONS)

    print("=" * 60)
    print(f"  SPRITE RENDERER  —  {MODE.upper()} MODE")
    print("=" * 60)
    if MODE == "mixamo":
        print("  Mixamo import reminder:")
        print("    File > Import > FBX  |  Scale=0.01  |  Pre/Post Rotation: ON")
        print()
    try:
        import PIL
        pil_status = f"Pillow {PIL.__version__} ✓  (no frame-count limit)"
        frame_limit = "unlimited"
    except ImportError:
        pil_status  = "Pillow NOT installed  ← install it to remove frame limits"
        frame_limit = f"{CHUNK_SIZE} per strip (Blender fallback)"

    print(f"  Anim:        {ANIM_NAME}")
    print(f"  Frames:      {FRAME_START}–{FRAME_END}  step={FRAME_STEP}  ({num_frames} frames)")
    print(f"  Resolution:  {FRAME_WIDTH}×{FRAME_HEIGHT}")
    print(f"  Renders:     {total_renders}  ({len(DIRECTIONS)} dirs × {num_frames} frames)")
    print(f"  Strip limit: {frame_limit}")
    print(f"  Pillow:      {pil_status}")
    print(f"  Output:      {OUTPUT_DIR}")
    print()

    # ── [1/6] Determine ortho_scale ───────────────────────────
    if MODE == "mixamo" and AUTO_FIT_CAMERA:
        print("[1/6] Auto-fitting camera (scanning bounding box)...")
        bbox = _scan_bbox_relative_to_center()
        ortho_scale = _calc_auto_ortho_scale(bbox) if bbox else ORTHO_SCALE
    else:
        saved = load_camera_config()
        ortho_scale = saved if saved is not None else ORTHO_SCALE
        src = "loaded from config" if saved is not None else "using ORTHO_SCALE default"
        print(f"[1/6] ortho_scale = {ortho_scale}  ({src})")

    print(f"  → ortho_scale = {ortho_scale:.3f}\n")

    # ── [2/6] Render setup ────────────────────────────────────
    print("[2/6] Render settings...")
    setup_render_settings()

    # ── [3/6] Camera ──────────────────────────────────────────
    print("[3/6] Camera...")
    cam = setup_camera(ortho_scale)

    # ── [4/6] Lighting + materials ────────────────────────────
    print("[4/6] Lighting + materials...")
    setup_lighting()
    make_materials_matte()

    # ── [5/6] Render each direction ───────────────────────────
    print(f"\n[5/6] Rendering...")
    dir_results = {}
    for dir_name, angle in DIRECTIONS:
        print(f"\n  --- {dir_name.upper()} ({angle}°) ---")
        render_direction(cam, dir_name, angle, OUTPUT_DIR)
        dir_results[dir_name] = combine_to_strip(dir_name, OUTPUT_DIR, num_frames)

    # ── [6/6] Cleanup, config, flip ───────────────────────────
    print("\n[6/6] Cleanup...")
    for dir_name, _ in DIRECTIONS:
        folder = os.path.join(OUTPUT_DIR, dir_name)
        if os.path.isdir(folder):
            shutil.rmtree(folder)
            print(f"  Deleted temp folder: {dir_name}/")

    save_camera_config(ortho_scale)

    # ── Summary ───────────────────────────────────────────────
    chunked  = CHUNK_SIZE > 0 and num_frames > CHUNK_SIZE
    n_parts  = math.ceil(num_frames / CHUNK_SIZE) if chunked else 1
    print("\n" + "=" * 60)
    print("  DONE!")
    print(f"  Mode:        {MODE}")
    print(f"  ortho_scale: {ortho_scale:.3f}")
    print(f"  Resolution:  {FRAME_WIDTH}×{FRAME_HEIGHT}")
    if chunked:
        print(f"  Output:      {n_parts} parts × 5 directions in {OUTPUT_DIR}")
        for i in range(1, n_parts + 1):
            label = f"{ANIM_NAME}{i}"
            print(f"    {label}/  ({label}_s, _n, _e, _ne, _se)")
    else:
        print(f"  Output:      {OUTPUT_DIR}")
        dirs_str = ", ".join(f"{ANIM_NAME}_{d}" for d, _ in DIRECTIONS)
        print(f"  Rendered:    {dirs_str}")
    print("=" * 60)

# When imported by render_launcher.py (headless batch mode) it sets
# bpy._launcher_mode = True before exec'ing this file, so main() is
# skipped here and the launcher calls it directly after scene setup.
if not getattr(bpy, "_launcher_mode", False):
    main()
