@echo off
:: Auto-generated by generate_render_bat.py
:: Character: robowalker  |  Mode: meshy
::
set BLENDER="C:\Program Files\Blender Foundation\Blender 5.0\blender.exe"
set SCRIPT="C:\Users\ryang\OneDrive\Documents\miniSWG\Tools\render_launcher.py"
set CHAR="C:\Users\ryang\OneDrive\Documents\miniSWG\Characters\newtoadd\robowalker"
set MODE=meshy

echo ============================================================
echo  Rendering robowalker sprites  [meshy mode]
echo ============================================================
echo.
echo [1/3] ATTACK
%BLENDER% --background --python %SCRIPT% -- ^
    --fbx "C:\Users\ryang\OneDrive\Documents\miniSWG\Characters\newtoadd\robowalker\fbx\fbxattack" ^
    --output "C:\Users\ryang\OneDrive\Documents\miniSWG\Characters\newtoadd\robowalker\attack" ^
    --anim attack --mode %MODE%
if errorlevel 1 goto :error
echo.
echo [2/3] IDLE
%BLENDER% --background --python %SCRIPT% -- ^
    --fbx "C:\Users\ryang\OneDrive\Documents\miniSWG\Characters\newtoadd\robowalker\fbx\fbxidle" ^
    --output "C:\Users\ryang\OneDrive\Documents\miniSWG\Characters\newtoadd\robowalker\idle" ^
    --anim idle --mode %MODE%
if errorlevel 1 goto :error
echo.
echo [3/3] RUN
%BLENDER% --background --python %SCRIPT% -- ^
    --fbx "C:\Users\ryang\OneDrive\Documents\miniSWG\Characters\newtoadd\robowalker\fbx\fbxrun" ^
    --output "C:\Users\ryang\OneDrive\Documents\miniSWG\Characters\newtoadd\robowalker\run" ^
    --anim run --mode %MODE%
if errorlevel 1 goto :error
echo.
echo ============================================================
echo  ALL DONE!  Check output folders in:
echo  C:\Users\ryang\OneDrive\Documents\miniSWG\Characters\newtoadd\robowalker
echo ============================================================
pause
exit /b 0

:error
echo.
echo  ERROR: Blender returned an error. Check output above.
pause
exit /b 1